Pikt/Pikt/urls.py
from django.contrib import admin
from django.urls import include, path
from Authentication import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from invoicing import views as invoicing_views
from ebay import views as ebay_views

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('sentry-debug/', trigger_error),
    path('admin/', admin.site.urls),
    path('', views.homeView.as_view()),
    path('login/', views.loginView.as_view(), name='login'),
    path('register/', views.registerView.as_view(), name='register'),
    path('account/', views.accountView.as_view(), name='account'),
    path('dashboards/', include('dashboards.urls')),
    path('ebay/', include('ebay.urls')),
    path('company/', include('company.urls')),
    path('account/upload_avatar/', views.uploadAvatarView.as_view(), name='upload_avatar'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboards/generate-quote/<int:customer_id>/', invoicing_views.generate_quote, name='generate_quote'),
    path('send-invoice/<int:invoice_id>/', invoicing_views.send_invoice, name='send_invoice'),
    path('save-ebay-policies/', ebay_views.SaveEbayPoliciesView.as_view(), name='save_ebay_policies'),
    path('set-parts-ebay-listed/', ebay_views.SetPartsEbayListedView.as_view(), name='mark_as_ebay_listed'),
    path('ebay-data-feed', ebay_views.EbayDataFeedView.as_view(), name='ebay_data_feed'),
    path('ebay_consent/redirect/', ebay_views.RedirectView.as_view(), name='redirect'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pikt/Authentication/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser, Group, Permission
from django.core.validators import RegexValidator
from company.models import Location

ROLE_CHOICES = (
    ('Admin', 'Admin'),
    ('Manager', 'Manager'),
    ('Employee', 'Employee'),
)

class funnelSubmission(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    yard_size = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    company = models.CharField(max_length=100)
    message = models.TextField()
    def __str__(self):
        return self.name


class User(AbstractUser):
    icon = models.ImageField(upload_to='profile_pics', null=True, blank=True)
    phone_regex = RegexValidator(
        regex=r'^\d{3}-\d{3}-\d{4}$',
        message="Phone number must be entered in the format: '999-999-9999'"
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=12, blank=True)  # validators should be a list
    messages = models.TextField(blank=True, default='[]')
    ebay_user_token = models.CharField(max_length=3000, blank=True)
    ebay_user_refresh_token = models.CharField(max_length=3000, blank=True)
    ebay_application_token = models.CharField(max_length=3000, blank=True)
    ebay_user_token_expiration = models.DateTimeField(null=True, blank=True)
    ebay_user_refresh_token_expiration = models.DateTimeField(null=True, blank=True)
    ebay_application_token_expiration = models.DateTimeField(null=True, blank=True)
    company = models.ForeignKey('company.Company', on_delete=models.CASCADE, null=True, blank=True, related_name='users')
    is_main_company_contact = models.BooleanField(default=False)
    role = models.CharField(choices=ROLE_CHOICES, max_length=10, default='Employee')
    u_pull_it_account = models.BooleanField(default=False)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, null=True, blank=True, related_name='users')

class templateImage(models.Model):
    image = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class templateIcon(models.Model):
    image = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

Pikt/Authentication/forms.py
from django import forms
from .models import funnelSubmission


class FunnelSubmissionForm(forms.ModelForm):
    YARD_SIZE_CHOICES = [
        ('', 'Select Yard Size...'),
        ('0-500 Vehicles', '0-500 Vehicles'),
        ('500-1000 Vehicles', '500-1000 Vehicles'),
        ('1000+ Vehicles', '1000+ Vehicles'),
    ]
    PAIN_POINT_OPTIONS = [
        ('Managing/Adding Parts Inventory', 'Managing/Adding Parts Inventory'),
        ('Selling Parts', 'Selling Parts'),
        ('Buying/Managing Vehicles', 'Buying/Managing Vehicles'),
        ('Managing Customers', 'Managing Customers'),
        ('Managing invoices/POs', 'Managing Invoices/POs'),
        ('Other', 'Other'),
    ]


    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'text-field w-input'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'text-field w-input'}))
    yard_size = forms.ChoiceField(choices=YARD_SIZE_CHOICES, initial='', widget=forms.Select(attrs={'disabled': 'disabled'}))
    company = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Company', 'class': 'text-field w-input'}))
    message = forms.ChoiceField(required=True, choices=PAIN_POINT_OPTIONS, widget=forms.RadioSelect)
    otherInput = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'text-field w-input', 'style': 'display:none;'}))

    class Meta:
        model = funnelSubmission
        fields = ['name', 'email', 'yard_size', 'company', 'message']

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'text-field w-input'}), label='')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'text-field w-input'}), label='')
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'text-field w-input'}), label='')
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First Name', 'class': 'text-field w-input'}), label='')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last Name', 'class': 'text-field w-input'}), label='')
    company = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Company', 'class': 'text-field w-input'}), label='')
    

Pikt/Authentication/views.py
from django.shortcuts import render
from .models import User
from django.contrib.auth import login
import os
from django.conf import settings
from django.http import HttpResponse
from django.views import View
from dotenv import load_dotenv
from .models import templateImage
from company.models import Company, Location
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
import json
from .forms import FunnelSubmissionForm, RegisterForm
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView
from django import forms
from django.contrib.auth.views import PasswordResetDoneView

from dashboards.models import PartPreference


context = {
    'main_logo': os.path.join(settings.BASE_DIR, 'assets', 'logo_transparent_large_black.png'),
    'years' : range(2024, 1969, -1),
    'colors': ['Black', 'White', 'Silver', 'Grey', 'Blue', 'Red', 'Brown', 'Green', 'Yellow', 'Gold', 'Orange', 'Purple'],
    'makes': ['Acura', 'Alfa Romeo', 'Aston Martin', 'Audi', 'Bentley', 'BMW', 'Bugatti', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Citroen', 'Dodge', 'Ferrari', 'Fiat', 'Ford', 'Geely', 'General Motors', 'GMC', 'Honda', 'Hyundai', 'Infiniti', 'Jaguar', 'Jeep', 'Kia', 'Koenigsegg', 'Lamborghini', 'Land Rover', 'Lexus', 'Maserati', 'Mazda', 'McLaren', 'Mercedes-Benz', 'Mini', 'Mitsubishi', 'Nissan', 'Pagani', 'Peugeot', 'Porsche', 'Ram', 'Renault', 'Rolls Royce', 'Saab', 'Subaru', 'Suzuki', 'Tesla', 'Toyota', 'Volkswagen', 'Volvo']
}

class MyView(View):
    def get(self, request):
        load_dotenv()
        context = {
            'APPLICATION_TOKEN': os.getenv('APPLICATION_TOKEN'),
            'USER_TOKEN': os.getenv('USER_TOKEN')
        }
        return render(request, 'index.html', context)
# Create your views here.

class homeView(View):
    def get(self, request):
        form = FunnelSubmissionForm()
        transparent_logo_large_white  = os.path.join(settings.BASE_DIR, 'assets', 'logo_transparent_large_white.png')
        context = {
            'form': form,
            'transparent_logo_large_white': transparent_logo_large_white
        }
        return render(request, 'home.html', context)

    def post(self, request):
        transparent_logo_large_white  = os.path.join(settings.BASE_DIR, 'assets', 'logo_transparent_large_white.png')
        form = FunnelSubmissionForm(request.POST)
        
        if form.is_valid():
            if form.cleaned_data['otherInput']:
                instance = form.save(commit=False)
                instance.message = form.cleaned_data['otherInput']
                instance.save()
            else:
                form.save()
            context = {
                'transparent_logo_large_white': transparent_logo_large_white
            }
            return render(request, 'funnel-success.html', context)  # replace 'success_url' with the name of the URL you want to redirect to after successful form submission
        else:
            transparent_logo_large_white  = os.path.join(settings.BASE_DIR, 'assets', 'logo_transparent_large_white.png')
            context = {
                'form': form,
                'transparent_logo_large_white': transparent_logo_large_white
            }
            return render(request, 'home.html', context)

class loginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('/dashboards/vehicles/')
        return render(request, 'login.html')

    def post(self, request):
        username = request.POST['Username']
        password = request.POST['Password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/dashboards/vehicles/')  # replace 'home' with the name of the view you want to redirect to after login
        else:
            # Invalid login
            return render(request, 'login.html', {'error': 'Invalid username or password'})

class registerView(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, 'register.html', {'form': form})
    
    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            company = form.cleaned_data['company']
            icon = '../static/images/default-avatar.webp'
            if User.objects.filter(email=email).exists():
                form.add_error('email', 'A user with this email already exists')
                return render(request, 'register.html', {'form': form})
            if User.objects.filter(username=username).exists():
                form.add_error('username', 'A user with this username already exists')
                return render(request, 'register.html', {'form': form})
            if Company.objects.filter(name=company).exists():
                form.add_error('company', 'A company with this name already exists')
                return render(request, 'register.html', {'form': form})
            company = Company.objects.create(name=company)
            PartPreference.objects.create(company=company, parts="A/C Compressor,Alternator,Axle Assy Fr (4WD w. Housing),Axle Assy Rear (w. Housing),Battery,Brake/Clutch Pedal,Brake Booster,Brake Rotor/Drum, Rear,Bumper Assy (Front) includes cover,Bumper Assy (Rear) includes cover,Caliper,Clutch Master Cylinder,Control Arm, Front Lower,Control Arm, Front Upper,Control Arm, Rear Lower,Control Arm, Rear Upper,Door Back (door above rear bumper),Door Front,Engine,Engine Computer,Engine Wiring Harness,Fender,Front Axle Assembly (4WD w Housing),Front Bumper Assembly (includes cover),Master Cylinder,Transmission,Windshield")
            company.save
            user = User.objects.create_user(username, email, password, first_name=first_name, last_name=last_name, icon=icon, company=company)
            user.role = "Admin"
            user.save()
            login(request, user)
            messages = json.loads(request.user.messages)
            messages.append('Welcome to Pikt!')
            request.user.messages = json.dumps(messages)
            request.user.save()
            return redirect('/dashboards/vehicles/')
        return render(request, 'register.html', {'form': form})

    
from dashboards.models import Customer
from invoicing.models import Invoice
from ebay.models import EbayPolicy, EbayCredential
from ebay.forms import EbayPolicyForm, EbayMIPCredentialsForm
class accountView(View):
    def get(self, request):
        payment_ebay_policy_form = EbayPolicyForm(initial={'company': request.user.company, 'policy_type': 'Payment'})
        payment_ebay_policy_form.fields['company'].widget = forms.HiddenInput()
        return_ebay_policy_form = EbayPolicyForm(initial={'company': request.user.company, 'policy_type': 'Return'})
        return_ebay_policy_form.fields['company'].widget = forms.HiddenInput()
        shipping_ebay_policy_form = EbayPolicyForm(initial={'company': request.user.company, 'policy_type': 'Shipping'})
        shipping_ebay_policy_form.fields['company'].widget = forms.HiddenInput()

        ebay_mip_credentials_form = EbayMIPCredentialsForm()
        

        ebay_credentials_exist = False
        if request.user.company.ebay_credentials:
            ebay_credentials_exist = True

        context = {
            'customer_count': Customer.objects.all().count(),
            'invoices_total': "{:.2f}".format(sum(invoice.total for invoice in Invoice.objects.filter(company=request.user.company) if invoice.total is not None)),
            'invoices': Invoice.objects.filter(company=request.user.company),
            'payment_ebay_policy_form': payment_ebay_policy_form,
            'return_ebay_policy_form': return_ebay_policy_form,
            'shipping_ebay_policy_form': shipping_ebay_policy_form,
            'ebay_mip_credentials_form': ebay_mip_credentials_form,
            'ebay_credentials_exist': ebay_credentials_exist,
            'messages': json.loads(request.user.messages),
        }
        return render(request, 'account.html', context)
    
    def post(self, request):
        first_name = request.POST.get('First-name')
        last_name = request.POST.get('Last-name')
        email = request.POST.get('Email-Address')
        phone_number = request.POST.get('Phone')

        user = request.user
        if first_name != '':
            user.first_name = first_name
        if last_name != '':
            user.last_name = last_name
        if email != '':
            user.email = email
        if phone_number != '':
            user.phone_number = phone_number
        user.save()

        # messages.success(request, 'Your account has been updated!')
        return redirect('account')
    
class uploadAvatarView(View):
    def post(self, request):
        if 'icon' in request.FILES:
            request.user.icon = request.FILES['icon']
            request.user.save()
            # messages.success(request, 'Avatar updated successfully')
        return redirect('account')

Pikt/Authentication/views/root.py
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

Pikt/Authentication/templates/funnel-success.html
<!DOCTYPE html>
<html>

<head>
    <title>Pikt</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <div class="presentation-hero-section wf-section">
        <div class="container">
            <div class="presentation-title-wrapper"><img
                    src="{% static 'images/logo_transparent_large_white.png' %}"
                    loading="lazy" style="opacity: 1;" alt=""
                    class="logo-presentation">
                <div>
                    
                    <div>
                        <h1 data-w-id="a854c0b2-01fc-e990-1029-182060e95531" style="opacity: 1;" class="display-heading-1">Thank you for joining the waitlist!</h1>
                        <div data-w-id="ed503702-153b-0192-1e6b-37d0374b7368" style="opacity: 1;" class="space-bottom">We look forward to working with you. You should be hearing from us shortly!</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="presentation-hero-bg"></div>
    </div>
    <div id="Presentation" class="presentation-section wf-section">
        <div class="container">
            <div class="presentation-category-wrapper">
                <h1 class="display-heading-2">In the meantime...</h1>
                <div>Check us out on social media!</div>
            </div>
            <div style="display:grid; grid-template-columns: 1fr 1fr; margin-right: 30%; margin-left: 30%;">
                <div style="display: flex; justify-content: center;">
                    <a href="https://www.instagram.com/pikt.parts?igsh=MnVmZ3U2aGx0aTN5&utm_source=qr">
                        <img style="height: 60px" src="{% static 'icons/instagram.svg' %}" loading="lazy" alt="" class="nav-icon">
                    </a>
                </div>
                <div style="display: flex; justify-content: center;">
                    <a href="https://www.facebook.com/share/7doFfuGeciz8WYfh/?mibextid=hu50Ix">
                        <img style="height: 60px" src="{% static 'icons/facebook.svg' %}" loading="lazy" alt="" class="nav-icon">
                    </a>
                </div>
            </div>

        </div>
    </div>
    <div class="presentation-section cta wf-section">
        <div class="container">
            <div class="presentation-cta">
                <h1 class="display-heading-2">Start selling today.</h1>
                <div class="space-bottom">Make selling parts that much easier.</div>
                <!-- <a
                    href="/login"
                    class="button cta w-button">Login</a> -->
            </div>
            <div class="footer"><a href=""
                    class="footer-link">Pikt</a>
        </div>
    </div>
    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=6057ab51530cb39d3fdac75d"
        type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
        <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
    <!--[if lte IE 9]><script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
</body>
<style>
    .presentation-hero-section {
        padding-top: 32px;
    }

    #funnel-form {
        display: flex;
        flex-direction: column;
        align-items: center;
        background-color: white;
        color: black;
        box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.1), 0 1px 3px rgba(0, 0, 0, 0.1);
        border-radius: 20px;
        padding: 20px;
    }
    .form-group {
        width: 100%;
    }
    #id_yard_size {
        margin: 10px;
        width: 100%;
    }
    #id_name {
        width: 100%;
    }
    #id_company {
        width: 100%;
        /* margin: 10px; */
    }
    .presentation-hero-bg {
        height: 100%;
    }
</style>
</html>

Pikt/Authentication/templates/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Pikt Login</title>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
</head>

<body class="authentication-page">
    <div class="authentication-module">
        <h2>Sign in</h2>
        <div class="authentication-form-block w-form">
            <form id="wf-form-Form" name="wf-form-Form" data-name="Form" method="post" class="authentication-form"
                aria-label="Form">
                {% csrf_token %}
                <div class="w-layout-grid authentication-grid">
                    <div><input type="text" class="authentication-field w-input" maxlength="256" name="Username"
                            data-name="Username" placeholder="Username" id="Username" required=""></div>
                    <div><input type="password" class="authentication-field w-input" maxlength="256" name="Password"
                            data-name="Password" placeholder="Password" id="Password" required=""></div><input
                        type="submit" value="Sign In" data-wait="Please wait..."
                        id="w-node-_4ebb5952-efb6-c0fb-2224-5e5b2d558992-6e0ee29f"
                        class="button button-small w-button"><label class="w-checkbox remember-me-field">
                        <div
                            class="w-checkbox-input w-checkbox-input--inputType-custom checkbox text-right w--redirected-checked">
                        </div>
                        <!-- <input type="checkbox" id="checkbox-2" name="checkbox-2" data-name="Checkbox 2" checked=""
                            style="opacity:0;position:absolute;z-index:-1"><span class="checkbox-label w-form-label"
                            for="checkbox-2">Remember me</span> -->
                    </label>
                    <a href="/accounts/password_reset" class="small-link">Forgot your password?</a>
                    <a href="/register" class="small-link">No account?&nbsp;Sign up</a>
                </div>
            </form>
            <div class="form-success w-form-done" tabindex="-1" role="region" aria-label="Form success">
                <div>Thank you! You have successfully Signed In. </div>
            </div>
            {% if error %}
                <div class="form-error" tabindex="-1" role="region" aria-label="Form failure">
                    <div>{{ error }}</div>
                </div>
            {% endif %}
        </div>
    </div><a href="/" class="back-to-home w-inline-block"><img
            src="https://assets.website-files.com/6057ab51530cb39d3fdac75d/6058beecd1bd3048e62f48d8_arrow-left.svg"
            loading="lazy" alt="" class="back-icon">
        <div>Back to Home</div>
    </a>
    <!-- <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=6057ab51530cb39d3fdac75d"
        type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script> -->
        <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
    <!--[if lte IE 9]><script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
</body>

</html>

Pikt/Authentication/templates/password-reset.html
<!DOCTYPE html>
<html>

<head>
    <title>Pikt Login</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="authentication-page">
    <div class="authentication-module">
        <h2>Password reset</h2>
        <div class="authentication-form-block w-form">
            <form id="wf-form-Form" name="wf-form-Form" data-name="Form" method="get" class="authentication-form"
                aria-label="Form">
                <div class="w-layout-grid authentication-grid"><input type="email" class="authentication-field w-input"
                        maxlength="256" name="Email" data-name="Email" placeholder="Email" id="Email" required=""><input
                        type="submit" value="Reset password" data-wait="Please wait..."
                        id="w-node-_4ebb5952-efb6-c0fb-2224-5e5b2d558992-b5cf89bd"
                        class="button button-small w-button"><a href="/login" class="small-link">or
                        sign in instead</a></div>
            </form>
            <div class="form-success w-form-done" tabindex="-1" role="region" aria-label="Form success">
                <div>Thank you! Please check your inbox.</div>
            </div>
            <div class="form-error w-form-fail" tabindex="-1" role="region" aria-label="Form failure">
                <div>Oops! Something went wrong while resetting your password.</div>
            </div>
        </div>
    </div><a href="/" class="back-to-home w-inline-block"><img
            src="https://assets.website-files.com/6057ab51530cb39d3fdac75d/6058beecd1bd3048e62f48d8_arrow-left.svg"
            loading="lazy" alt="" class="back-icon">
        <div>Back to Home</div>
    </a>
    <!-- <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=6057ab51530cb39d3fdac75d"
        type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script> -->
        <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
    <!--[if lte IE 9]><script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
</body>

Pikt/Authentication/templates/register.html
<!DOCTYPE html>
<html>

<head>
    <title>Pikt Login</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
</head>

<body class="authentication-page">
    <div class="authentication-module">
        <h2>Sign up</h2>
        <form method="post" action="{% url 'register' %}">
            {% csrf_token %}
            {% if error %}
                <li>{{ error }}</li>
            {% endif %}
            {{ form.as_p }}
            <button class="button" type="submit">Sign up</button>
        </form>
    </div><a href="/" class="back-to-home w-inline-block"><img
            src="https://assets.website-files.com/6057ab51530cb39d3fdac75d/6058beecd1bd3048e62f48d8_arrow-left.svg"
            loading="lazy" alt="" class="back-icon">
        <div>Back to Home</div>
    </a>
    <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
</body>

</html>